### ISSUE TITLE
Accessing cal certs

### ISSUE THREAD

**Issue by btc721** [chad-m-carlson/arrow-tech#22]
On batch 3 I have 3 different models and three different certificate numbers.  It's really strange. When I first went in I couldn't get past the first certificate.  Or I'd have to enter it twice and then I could go the next one.  If I didn't edit the calibration equipment it just didn't let me go past.  But there was no error message or anything.   Right now it works fine and all the certificates show up.

**Comment by chad-m-carlson** [comment]
This should be fixed. Good find. It was literally one line of code on the wrong side of a '}'

**Comment by btc721** [comment]
I made a whole new batch up.  The issue I noticed was fixed.
