### ISSUE TITLE
Failure report

### ISSUE THREAD

**Issue by btc721** [chad-m-carlson/arrow-tech#30]
If there are no failed dosimeters, and you click failure reports in the reports section,  the screen just goes blank and you can't go anywhere.  If I hit refresh in the browser it goes back to normal.

**Comment by chad-m-carlson** [comment]
This should work now. An all failing batch would have the same bug but on the CoC so I fixed that.

If you want I can put an empty row that says "No failing(or passing) dosimeters" or something to that effect.

**Comment by btc721** [comment]
I like the idea of the empty row with "No failing(or passing) dosimeters"  That might make it easier for people.

**Comment by chad-m-carlson** [comment]
Done
