### ISSUE TITLE
batch numbers

### ISSUE THREAD

**Issue by chad-m-carlson** [chad-m-carlson/arrow-tech#37]
How should we deal with batch numbers? Assign them automatically or manually?

If they are automatic there is no risk of having a duplicate batch number.

**Comment by btc721** [comment]
Automatically is fine.

**Comment by chad-m-carlson** [comment]
So if that's the case, let me know which batches I can just delete, and which ones you want me to reassign batch numbers too since we have a bunch of random ones in the production database.

**Comment by btc721** [comment]
Keep batch 1, 53 and 325-331.  There will be a big batch going in tomorrow and one next week, so there will be a good test of the system.

**Comment by chad-m-carlson** [comment]
Updated batch numbers as follows:

**Old = New**
1 = 1
53 = 2
325 = 3
326 = 4
327 = 5
328 = 6
329 = 7
330 = 8
331 = 9
