### ISSUE TITLE
Batch Report

### ISSUE THREAD

**Issue by chad-m-carlson** [chad-m-carlson/arrow-tech#43]
I just threw the batch report together a long time ago mainly to help me see how things were working and it kind of turned into a bit more than that.

What would you like to see in the batch report?

**Comment by btc721** [comment]
I don't need the calibration tech or the date received in it.  Otherwise I think it's a pretty useful summary.

**Comment by chad-m-carlson** [comment]
I might just replace those two things with if there is a custom tolerance (and what it is) and if the hermetic seal is required. They might not show up on every row but at least be visible like how I have the total passing and failing dosimeters.
