### ISSUE TITLE
Numerical order in batch report

### ISSUE THREAD

**Issue by btc721** [chad-m-carlson/arrow-tech#45]
Can you put things in numerical order on the batch report?  It makes it easier to find something to edit in big batches.

**Comment by chad-m-carlson** [comment]
By dosimeter serial number?

**Comment by btc721** [comment]
I'm not sure the best way to do it.   I do want them in order by serial number, but with multiple dosimeter model I like it when all of the models are grouped together.   

So, can all the dosimeters in a single model be grouped together in numerical order by serial number?  And then the next model in numerical order...

**Comment by chad-m-carlson** [comment]
This should work. I don't think we have any batches in the production DB that this will affect but it seems to work fine in development.
