### ISSUE TITLE
Failure report

### ISSUE THREAD

**Issue by btc721** [chad-m-carlson/arrow-tech#46]
Once something fails one test is there a way to make all other tests N/A for that dosimeter.  Once something fails in calibration we just stop testing it, so we may not have any data for some of the tests.  If nothing is entered it just shows failure on the failure report.  It's hard to tell what it really failed.  The batch I'm looking at is 327.   I'd rather do this with programming, we can just run all the tests all the time if that's the only way.   Sometimes there are hundreds of dosimeters that fail and it's a lot of work to run multiple tests that don't matter.

**Comment by chad-m-carlson** [comment]
Doing some initial testing with this, and it shouldn't be that hard to do. 

Do you normally enter in ALL the passing dosimeters, then all the ones that failed at the EL test, then all the ones that failed at the ACC test etc...? I'm trying to prevent the amount of inputs required and still allow you to only use the keypad to navigate the whole form. If they aren't entered in any particular order, it will definitely add some extra keystrokes to get through all the pass/fail checkboxes and select/de-select them.

**Comment by btc721** [comment]
All the passing dosimeters of a dosimeter model are entered first.   The failures don't get entered in any particular order. They probably could be if it makes the form simpler.
